LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY BG IS
PORT(B:IN STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SEL: IN STD_LOGIC;
	 G:OUT STD_LOGIC_VECTOR (3 DOWNTO 0)
	 );
END ENTITY;

ARCHITECTURE A_BG OF BG IS
SIGNAL AUX: STD_LOGIC_VECTOR (3 DOWNTO 0);
BEGIN
	PROCESS (SEL, B, AUX)
	BEGIN
		CASE SEL IS
		WHEN '0' =>
			AUX <= TO_STDLOGICVECTOR(TO_BITVECTOR(B) SRL 1);
			G <= B XOR AUX;
		WHEN OTHERS =>
			G(3) <= B(3);
			G(2) <= B(2) XOR G(3);
			G(1) <= B(1) XOR G(2);
			G(0) <= B(0) XOR G(1);
		END CASE;
	END PROCESS;
END A_BG;
