LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
ENTITY PRACTICA1 IS
PORT(A,B: IN STD_LOGIC;
C,D,E,F,G,H,I,J: OUT STD_LOGIC
);
END ENTITY;
ARCHITECTURE A_P1 OF PRACTICA1 IS
BEGIN
C <= A OR B;
D <= A AND B;
E <= A NAND B;
F <= A NOR B;
G <= A XOR B;
H <= A XNOR B;
I <= NOT A;
J <= NOT B;
END A_P1;
