LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY SR IS
PORT (
    A, B: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
	C: IN STD_LOGIC;
    SR: OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
    CF: OUT STD_LOGIC
	);
END ENTITY SR;

ARCHITECTURE A_SR OF SR IS
SIGNAL CI: STD_LOGIC_VECTOR(2 DOWNTO 0);
SIGNAL EB: STD_LOGIC_VECTOR(3 DOWNTO 0);
ATTRIBUTE SYNTHESIS_OFF OF CI: SIGNAL IS TRUE;

BEGIN

	EB(0) <= B(0) XOR C;
	SR(0) <= A(0) XOR EB(0) XOR C;
	CI(0) <= (A(0) AND EB(0)) OR (A(0) AND C) OR (EB(0) AND C);

	EB(1) <= B(1) XOR C;
	SR(1) <= A(1) XOR EB(1) XOR CI(0);
	CI(1) <= (A(1) AND EB(1)) OR (A(1) AND CI(0)) OR (EB(1) AND CI(0));

	EB(2) <= B(2) XOR C;
	SR(2) <= A(2) XOR EB(2) XOR CI(1);
	CI(2) <= (A(2) AND EB(2)) OR (A(2) AND CI(1)) OR (EB(2) AND CI(1));

	EB(3) <= B(3) XOR C;
	SR(3) <= A(3) XOR EB(3) XOR CI(2);
	CF <= (A(3) AND EB(3)) OR (A(3) AND CI(2)) OR (EB(3) AND CI(2));

END A_SR;

