LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
ENTITY MUX IS
PORT (A,B: IN STD_LOGIC;
      SEL: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
	  Z: OUT STD_LOGIC
	  );
END ENTITY;

ARCHITECTURE A_MUX OF MUX IS
BEGIN

WITH SEL SELECT
   Z <= A OR B WHEN "000",
        A AND B WHEN "001",
		A NOR B WHEN "010",
		A NAND B WHEN "011",
		A XOR B WHEN "100",
		A XNOR B WHEN "101",
		NOT A WHEN "110",
		NOT B WHEN OTHERS;

END A_MUX;
