LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY CM IS
PORT (A, B: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
	I, MA, ME: OUT STD_LOGIC
);
END ENTITY;

ARCHITECTURE A_CM OF CM IS
BEGIN
	I<='1' WHEN (A=B) ELSE '0';
	MA<='1' WHEN (A>B) ELSE '0';
	ME<='1' WHEN (A<B) ELSE '0';
END A_CM;
